### PR TITLE
Update to version 1.0.3

### PR DESCRIPTION
**Pull request by StephanStanisic**
v1.0.3
- Adds support for EM6551
- Adds support for EM6552
- Adds support for EM6556
- Adds support for EM6570
- Adds support for EM6580
- Adds support for EM6581
- Adds support for EM6582
- Adds support for EM6590
- Adds support for EM6592

### CODE REVIEW

**Comment by RobinBol** [comment]
Thanks for the PR! Can you tell me what the original manufacturer of the EM6582 Bewegingsmelder is? It has a different `manufacturerId`, namely 278 (which I could not quickly trace to a manufacturer).

**Comment by StephanStanisic** [comment]
The EM6582  is a rebranded version of the HSP02 from Everspring. In the
com.eversping app from ralf he also uses 278 instead of 96. When I tested
the app on our homey it worked.

Op do 19 apr. 2018 om 10:40 schreef Robin Bolscher <notifications@github.com

**Comment by RobinBol** [comment]
@StephanStanisic we'd like to transfer the ownership of the app to you if you'd like. Could you send me an email at robin@athom.com with the Athom Account to which it can be transferred? Thanks!

**Comment by RobinBol** [comment]
@StephanStanisic I don't seem to get any reply back on the emails I've sent you, could you check this please?

**Comment by StephanStanisic** [comment]
I have not recieved any emails... Could you confirm that your sending
emails to either stephanstanisic@gmail.com, me@stst.ga or
stephanstanisic@outlook.com?

**Comment by RobinBol** [comment]
The emails were sent to the email address to which the app was transferred!

**Pull request merged**
